@echo off
cd /d "%~dp0"
echo Starting local dev server...
start cmd /k "npm start"
echo Waiting for server to start...
ping 127.0.0.1 -n 5 > nul
echo Launching Word...
npx office-addin-dev-settings sideload E:\word_addins\manifest.xml -a word